// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nebulix/storage/v1/file.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// File defines the File message.
type File struct {
	Merkle    string   `protobuf:"bytes,1,opt,name=merkle,proto3" json:"merkle,omitempty"`
	Owner     string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	FileSize  int64    `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Providers []string `protobuf:"bytes,4,rep,name=providers,proto3" json:"providers,omitempty"`
	Start     int64    `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	BinId     uint64   `protobuf:"varint,6,opt,name=bin_id,json=binId,proto3" json:"bin_id,omitempty"`
	Replicas  int64    `protobuf:"varint,7,opt,name=replicas,proto3" json:"replicas,omitempty"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa470856b6e8fa61, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_File.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return m.Size()
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetMerkle() string {
	if m != nil {
		return m.Merkle
	}
	return ""
}

func (m *File) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *File) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *File) GetProviders() []string {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *File) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *File) GetBinId() uint64 {
	if m != nil {
		return m.BinId
	}
	return 0
}

func (m *File) GetReplicas() int64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func init() {
	proto.RegisterType((*File)(nil), "nebulix.storage.v1.File")
}

func init() { proto.RegisterFile("nebulix/storage/v1/file.proto", fileDescriptor_fa470856b6e8fa61) }

var fileDescriptor_fa470856b6e8fa61 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x3b, 0x4e, 0xc4, 0x30,
	0x14, 0x45, 0x63, 0xf2, 0x61, 0xe2, 0xd2, 0xe2, 0x63, 0xf1, 0xb1, 0x22, 0xaa, 0x54, 0x89, 0x22,
	0x76, 0x40, 0x81, 0x44, 0x1b, 0x3a, 0x9a, 0x51, 0x42, 0x1e, 0xe8, 0x09, 0x13, 0x5b, 0xb6, 0x09,
	0x30, 0xab, 0x60, 0x39, 0x2c, 0x81, 0x72, 0x4a, 0x4a, 0x94, 0x6c, 0x04, 0xe5, 0x33, 0x9a, 0xf2,
	0xdc, 0xab, 0x77, 0x9f, 0x74, 0xe8, 0x65, 0x0b, 0xf5, 0x9b, 0xc4, 0x8f, 0xdc, 0x3a, 0x65, 0xaa,
	0x67, 0xc8, 0xbb, 0x22, 0x7f, 0x42, 0x09, 0x99, 0x36, 0xca, 0x29, 0xc6, 0x96, 0x3a, 0x5b, 0xea,
	0xac, 0x2b, 0xae, 0xbe, 0x09, 0x0d, 0x6e, 0x51, 0x02, 0x3b, 0xa1, 0xd1, 0x2b, 0x98, 0x17, 0x09,
	0x9c, 0x24, 0x24, 0x8d, 0xcb, 0x85, 0xd8, 0x11, 0x0d, 0xd5, 0x7b, 0x0b, 0x86, 0x1f, 0x4c, 0xf1,
	0x0c, 0xec, 0x9c, 0xc6, 0xe3, 0xf0, 0xda, 0xe2, 0x06, 0xb8, 0x9f, 0x90, 0xd4, 0x2f, 0x57, 0x63,
	0x70, 0x8f, 0x1b, 0x60, 0x17, 0x34, 0xd6, 0x46, 0x75, 0xd8, 0x80, 0xb1, 0x3c, 0x48, 0xfc, 0x34,
	0x2e, 0xf7, 0xc1, 0x38, 0x68, 0x5d, 0x65, 0x1c, 0x0f, 0xa7, 0xb3, 0x19, 0xd8, 0x31, 0x8d, 0x6a,
	0x6c, 0xd7, 0xd8, 0xf0, 0x28, 0x21, 0x69, 0x50, 0x86, 0x35, 0xb6, 0x77, 0x0d, 0x3b, 0xa3, 0x2b,
	0x03, 0x5a, 0xe2, 0x63, 0x65, 0xf9, 0xe1, 0xfc, 0x66, 0xc7, 0x37, 0xc5, 0x4f, 0x2f, 0xc8, 0xb6,
	0x17, 0xe4, 0xaf, 0x17, 0xe4, 0x6b, 0x10, 0xde, 0x76, 0x10, 0xde, 0xef, 0x20, 0xbc, 0x87, 0xd3,
	0x9d, 0x87, 0xbd, 0x09, 0xf7, 0xa9, 0xc1, 0xd6, 0xd1, 0x24, 0xe2, 0xfa, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0x1e, 0xeb, 0x3e, 0x17, 0x29, 0x01, 0x00, 0x00,
}

func (m *File) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *File) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *File) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Replicas != 0 {
		i = encodeVarintFile(dAtA, i, uint64(m.Replicas))
		i--
		dAtA[i] = 0x38
	}
	if m.BinId != 0 {
		i = encodeVarintFile(dAtA, i, uint64(m.BinId))
		i--
		dAtA[i] = 0x30
	}
	if m.Start != 0 {
		i = encodeVarintFile(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Providers) > 0 {
		for iNdEx := len(m.Providers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Providers[iNdEx])
			copy(dAtA[i:], m.Providers[iNdEx])
			i = encodeVarintFile(dAtA, i, uint64(len(m.Providers[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.FileSize != 0 {
		i = encodeVarintFile(dAtA, i, uint64(m.FileSize))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintFile(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Merkle) > 0 {
		i -= len(m.Merkle)
		copy(dAtA[i:], m.Merkle)
		i = encodeVarintFile(dAtA, i, uint64(len(m.Merkle)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFile(dAtA []byte, offset int, v uint64) int {
	offset -= sovFile(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *File) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Merkle)
	if l > 0 {
		n += 1 + l + sovFile(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovFile(uint64(l))
	}
	if m.FileSize != 0 {
		n += 1 + sovFile(uint64(m.FileSize))
	}
	if len(m.Providers) > 0 {
		for _, s := range m.Providers {
			l = len(s)
			n += 1 + l + sovFile(uint64(l))
		}
	}
	if m.Start != 0 {
		n += 1 + sovFile(uint64(m.Start))
	}
	if m.BinId != 0 {
		n += 1 + sovFile(uint64(m.BinId))
	}
	if m.Replicas != 0 {
		n += 1 + sovFile(uint64(m.Replicas))
	}
	return n
}

func sovFile(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFile(x uint64) (n int) {
	return sovFile(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *File) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFile
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: File: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: File: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Merkle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Merkle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
			}
			m.FileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Providers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Providers = append(m.Providers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BinId", wireType)
			}
			m.BinId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BinId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			m.Replicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replicas |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFile(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFile
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFile(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFile
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFile
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFile
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFile
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFile
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFile
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFile        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFile          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFile = fmt.Errorf("proto: unexpected end of group")
)
